[*
   $ENV{__EMB_EXTRATITLE}="Various Scripts";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Some scripts, helpers and experiments that don't quite fit the other categories.</p>

<H3>Commands</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.various/">Git
    View of this section / Download</a></p>


<ul>
   <li><B>ALARM</B> (mostly acoustic environmental damage, for use with waitcond)
   <li><B>ALERTOSD</B> (using the on-screen display to print an alert)
   <li><B>append.p</b> (append files to similar named files in another dir, knows gzip;
        though mostly I just use mc for moving files into an archive dir and 
        appending files in case of collisions)
   <li><B>df.minfree</b> (checks free space and warns if lower than requested)
   <li><B>diff.p</b> (diff wrapper knowing about gzip)
   <li><b>gzip.r</b>, <b>gzip.rfix</B> (gzip -r with some exceptions; archive cleanup after gzip -r)
   <li><b>gunzipmemberextract</b> (experimental demo on how to extract gzipped appended members from
        a corrupted gzip file - a bit painful, but not impossible; still the gzip format shows its
        age and its deficiencies; if only some bzip2 modes would trade space inefficiency for more speed).
   <li><b>mt_dir</b> (configures directory short names and invokes one of echo/cd/mc; see
        also the nico_cd stack in the shell function section)
   <li><b>paradj</b> (format or justify a text; modified from J. Duque; can now skip \ 
        to format perl double quoted text for output)
   <li><b>repeat</b> (when I'm too lazy to write a while ... do; command; done loop)
   <li><b>sanitize_filenames</b> (rename files containing certain characters, umlauts,
       etc; superseeded by myrename)
   <li><b>sleep.p</b> (select-based sub-second sleep example)
   <li><b>sleepuntil</b> [ -c COMMAND] TIMESPEC ... sleeps until TIMESPEC, then 
       optionally execute the previously defined command. Knows some short-hand 
       notations like sleepuntil +20s or sleeptuntil 16:00.
   <li><b>unescape.pl</b> (modified version of Guide de Rosa's unescape; strip 
       some of the noise from script's typescript sessions logs; tries to strip
       e.g. vi sessions from the logs to increase their usability)
   <li><b>watchfloat</b> (write background command output to a floating region of a tty)
</ul>

<p>See also:</p>
<ul>
   <li><B>addcr/foldlf/remcr</B> - adding/removing umlauts or cr from files, (placed into html section
     due to the use of sub.mime)
   <li>some notes on a work-around for using <b>fdupes</b> for duplicate detection and relinking
   <li>some helper for <B>printing</b> and coping with gnome-gtk print making a mess of
     Unix basics like the possibility of printing via pipelines (in this section)
</ul>


[*}*][# MUST BE AT EOF! #]
