[*
   $ENV{__EMB_EXTRATITLE}="HTML";
   $ENV{__EMB_EXTRAMETA}="mostly old-style scripts to create/parse/maintain HTML files and sites, including book generation for e.g. printout and whole site diffs";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Commands  dealing with HTML. Most of these are pretty ancient,  but
sometimes still surprisingly useful.</p>

<H3>Major Commands (early 90's style)</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.HTML/">Git
    View of this section / Download</a></p>


<ul>
   <li><B>COLLECT</B> turns a set of html files into a single html document.
   <li><B>DIFF, DIFFTREE</B> diffs single html documents or whole site trees.
   <li><b>htmlcheck / htmlchek</b> is a truly ancient but handy html validator; 
       I think the configuration and some suppression of warnings was all I changed.
   <li><B>LINKS</B> extracts the links from an HTML document in HTML or list format
       for further processing. Does try basic guessing for form-based links.
   <li><B>XLINKS</B> another link extractor with its reporting geared as a first
       step for spidering.
   <li><b>db_cgi.p</b> is the retired DBFW's grab-bag of utility functions 
      (DBFW - a simple textual tagged database framework based on pipe filters
       which was also usable as CGI).
      Some scripts may still depend on one or the other of these functions.
   <li><b>dir2html.pl</b> provides old style configurable dirtree filelist generation
      using .name and .skip files for control. 
</ul>

<p>Of  course,  there are better ways than an early 90's mix  of  code
riddled  with  html  scraps. Think e.g. MVC and  templates  and  we've
advanced  to the late 90's: <b>dir2array</b> just guts the  convoluted
(and  inherently  buggy aka "heuristic") dir2html.pl and  stops  after
collecting  the filelist information. Feed that to an embperl template
(gitfilelist.epl),  and  include  that template from  any  phtml  page
requiring   a  filelist.  Way  more  flexible/extensible,  dreamy   to
maintain, less buggy and shorter to boot.</p>

<p  class=anno>The  directory dir.dir2array contains the early  August
'09  embperl  templates (incl. gitfilelist.epl) for my github site  as
well  as the script to statically translate the embperl pages to plain
html,  copy files contents as specified by a tree of symlinks,  commit
them  to a local git and finally push the differences to github.  Note
that  commandline embperl invoked from embpexec isn't quite as  modern
and  comfortable as embperl running within the webserver: this affects
both   invoking  embperl  and  the  searching/loading   of   baseclass
templates.</p>


[*}*][# MUST BE AT EOF! #]
