#!/bin/sh
# syntax check for html pages
# remember to strip crlf before testing!

# PJ TMP
export HTMLCHEK
HTMLCHEK=${HTMLCHEK:-/usr/local/dist/DIR/htmlchek}
[ ! -d "$HTMLCHEK" ] && HTMLCHEK=/usr/proj/infosys/bin
[ ! -d "$HTMLCHEK" ] && HTMLCHEK=$HOME/bin

# sugar=1: adds filenames to output
$HTMLCHEK/htmlchek.pl configfile=$HTMLCHEK/htmlcheck.tum.cfg $* | \
perl -e 'while(<>) {
           # ignore common bugs and abuse from defective editors
           $old=$_;
           s/.*?unquoted non-alphanumeric option value "([-+]\d+|[a-z0-9]*)".*//i;
           s/.*?Null <x>...<\/x> element Warning.*on tag \/(A|P|TD|.L)( .*|$)//i;
	   s/.*?Null reference option value ERROR! at line.*on tag A, option HREF.*//i;
	   s/.*?Warning! Jump from header level.*//i;
	   # allow netscape: <LI></LI><UL>... instead of correct <LI><UL>...</LI>
	   s/.*?Tag in .*?list occurred outside <(LI|DT|DD)>.*on tag (OL|UL|P|DL|BR|DIV|H.)( .*|$)//i;
	   s/.*?Disallowed tag in <body>...<\/body> ERROR!.*on tag link.*//i;
	   s/.*?tag, which is not low-level markup, nested in.*//i;
	   s/.*?empty list .* error.*//i;
	   s/.*?Was a dangling file-local reference "#" ERROR! at END.*//i;
	   s/.*?Non-whitespace outside <LI> in list.*//i;
	   s/.*?Tag in list occurred outside <LI>.*//i;
	   s/.*?Missing option value ERROR! at.*on tag IMG, option BORDER.*//i;
	   s/.*?Multiple <H1> headings.*Warning.*//i;
	   s/Disallowed tag in <head>...<\/head> ERROR! .* tag STYLE.*//i;
	   s/<STYLE> outside of <styles>...<\/styles> ERROR!.*//i;
	   s/CLASS not recognized as an option.*//i;
	   $_="" if not /\S/ and $old=~/\S/;
	   print
	}'
