[*
   $ENV{__EMB_EXTRATITLE}="TEMPLATE";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>This toolbox compartment contains the foo for doing bar (enjoying the zen of being just an empty template, waiting for reuse).</p>

<p class=anno>If you really want to see a copy of
the code generating the mark-down README.md for github, 
index.html pointers and the user pages documentation tree,
you can find a mothballed copy in
<a href="http://github.com/jakobi/script-archive/tree/master/cli.HTML/dir.dir2array/">cli.HTML/dir.dir2array</a>.</p>

<H3>Major Commands</H3>

<ul>
      <li><B>foo</B> is a bar
</ul>


[*}*][# MUST BE AT EOF! #]
