[*
   $ENV{__EMB_EXTRATITLE}="VIM (Placeholder)";
   $ENV{__EMB_EXTRAMETA}="commands to use vim in pipes both as vimscript and interactively as well as vim macros and functions";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>I  still  want to finish some macros and finally split my grab  bag
vim script file into presentable sections. Don't hold your breath.</p>

<H3>Files of Interest</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/vim/">Git
    View of this section / Download</a></p>


<ul>
   <li>shell scripts
      <ul> 
         <li>experimental: <b>vimscript</b> uses vim as interpreter for file containing
            non-interactive vim script. Can be used with pipes. Note that the
            script still requires a TTY due to short-comings of vim's head-less mode.
            For the time being, do <i>not</i> try to run multiple scripts in parallel; 
            the tempfile handling needs fixing (bash; full rewrite of the original vimsh 
            vimscript example). Published as 
            <a href="http://www.vim.org/scripts/script.php?script_id=2768">vimscript#2768</a> ).
        <li><b>pipe.vim</b> aka <b>vimpipe</b> (interactively use vim within a pipe, 
            e.g. for <tt>grep|pipe.vim|Grep.xchange</tt>. It also allow end-of-pipe
            style uses like <tt>find|xargs pipe.vim</tt>, editing all files being 
            passed as arguments from xargs, with help and the contents of stdin 
            available in the last buffer. Note that both pipe.vim and vimless
            do <i>wait for the end of input</i> from earlier pipe stages. Published as 
            <a href="http://www.vim.org/scripts/script.php?script_id=2769">vimscript#2769</a> .
        <li><b>vimless</b> (similar, but for the last stage of a pipe, slightly preconfigured
            to implement a less-clone capable of syntax highlighting. Like pipe.vim, it can 
            also be wrapped by e.g. xargs. Simple vim options can also be placed in
            VIMLESSOPT, e.g. export VIMLESSOPT='-c "set ft=perl"')
      </ul>
   <li>vim scripts
      <ul>
         <li>to be added: configuration files
         <li>to be added: vimsh with pty3 + urxvt patch (vimsh for interactive commands 
             and improved session subscripts)
         <li>to be added: vim scripts (after a clean up and split of .vimrc and 
             my function library file)
      </ul>
</ul>



[*}*][# MUST BE AT EOF! #]
