[*
   $ENV{__EMB_EXTRATITLE}="Mail scripts";
   $ENV{__EMB_EXTRAMETA}="a mime-capable patched grepmail";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Some  support  scripts for dealing with mail. Mlnn, the mutt  setup
and  the procmail setup is probably way too specific, so I'll  exclude
it for now (<i>is procmail still being actively maintained at all??</i>)</p>

<H3>Commands</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.mail/">Git
    View of this section / Download</a></p>


<ul>
   <li><b>mygrepmail</b>. <u>Update 9/09</u>: I'm happy to report spotting
       5.3034 on CPAN from 8/09. It's only a small diff for one file,
       but a giant leap for mailkind and this project. Or something like 
       that :). The inclusion of my MIME/UTF sketch below is still at the 
       TODO level. See also David's official sites on 
       <a href="http://code.google.com/p/grepmail/">google code</a>
       (old: <a href="http://grepmail.sf.net">Sourceforge</a>) and
       <a href="http://cpansearch.perl.org/src/DCOPPIT/">CPAN</a>.
       
       <p class=anno>The original code's strictly functional and a pleasure
       to read. Partly because of this I'm still unwilling to fork this one
       for real. Then again, it's a pity that the classic grepmail doesn't 
       know about MIME at all. So here's a modified interim version as a 
       proof of concept that de-mimes anything greppable just before the grep
       while by default
       returning the original email for further processing.</p>
  
       <p class=anno>Note that there 
       probably still are some 'modern times' problems with e.g. encoding 
       mixtures of body parts and headers (with specified or unspecified!!
       differing charset encodings) within and between mails: But it should
       work well enough for grepping against UTF8, ASCII and LATIN1 header/
       body-part mixes, at least for the common subset plus German umlauts, 
       which should be standardized for the grep as ae, oe, ue, and the like.
       Note that for unspecified charset encodings, we've nice conflicts 
       between 8bit LATIN1 umlauts above 0xA0 and UTF8, possibly leading
       to too many character remappings to ae&amp;co (which could be
       worked-around by also remapping the grep pattern - if in doubt,
       add a false hit). As an aside see also Egmont's issue on sf.net
       about perl's native charset encoding/transcoding capabilities, which
       could be used to smash the string representations of the parts of an 
       email to a single specific encoding for the final grep).</p>
</ul>


[*}*][# MUST BE AT EOF! #]
