[*
   $ENV{__EMB_EXTRATITLE}="Mail scripts";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Some  support  scripts for dealing with mail. Mlnn, the mutt  setup
and  the procmail setup is probably way too specific, so I'll  exclude
it for now (<i>is procmail still being actively maintained at all??</i>)</p>

<H3>Commands</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.mail/">Git
    View of this section / Download</a></p>


<ul>
   <li><b>mygrepmail</b>. <u>Update 9/09</u>: I'm happy to report spotting
       5.3034 on CPAN from 8/09. It's only a small diff for one file,
       but a giant leap for mailkind and this project. Or something like 
       that :). The inclusion of my MIME/UTF sketch below is still at the 
       TODO level. The official sites on 
       <a href="http://grepmail.sf.net">Sourceforge</a> and
       <a href="http://cpansearch.perl.org/src/DCOPPIT/">CPAN</a>.
       
       <p class=anno>The original code's strictly functional and a pleasure
       to read. Partly because of this I'm still unwilling to fork this one
       for real. Then again, it's a pity that the classic grepmail doesn't 
       know about MIME at all. So here's a modified interim version as a 
       proof of concept that de-mimes anything greppable just before the grep
       while by default
       returning the original email for further processing. Note that there 
       probably still are some 'modern times' problems with e.g. encoding 
       mixtures of body parts and headers (with specified or unspecified!!
       differing charset encodings) within and between mails. But it should
       work well enough for UTF8, ascii and latin1 mixes, at least for the
       common subset plus German umlauts, which should be standardized
       for the grep as ae, oe, ue, and the like.</p>
</ul>


[*}*][# MUST BE AT EOF! #]
