[*
   $ENV{__EMB_EXTRATITLE}="Process Handling";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Some  scripts  for  dealing  with  processes  and   process-related
events.</p>

<p>In  theory extending waitcond to allow D-BUS events might look like
a  good idea. But without a proper usage scenario I'm a bit  hesistant
to  hack  waitcond and in addition make it depend on external  modules
(even if only optional).</p>

<H3>Major Commands</H3>

<ul>
   <li><b>waitcond</b> (perl) - test or wait for an event. Like tagls/Grep.pm, 
       this one also offers boolean expressions, this time on top of a 
       language of tests including
   <ul>
      <LI>grep in files or command output
      <LI>successful execution of shell commands
      <LI>host pinging
      <LI>(dis)appearance of files
      <LI>(dis)appearance of processes in ps output
      <LI>threshhold-based file modification time
      <LI>threshhold-based cpu/net/disk idleness
   </ul>
       See waitcond.dbus.README for ideas on using dbus-events with waitcond
       (waiting for events like 'ping', HAL, FUSE, Desktop-Notifications).
       You will probably want to combine waitcond with some notification tool 
       like the trumpets of Jericho (or just ALARM, maybe also something boring 
       like eMail or SMS) to be indeed sucessfully notified of the fact that your 20 hour 
       compile just failed with a syntax error after just 58 minutes...<BR>
   <li>A simplified variant with different history and codebase is
       <b>fwait/pwait</b>, which is probably the most authentic and still used version
       of my original boolean regex patch that I created for a small perl fulltext
       indexer (96-97 maybe?). Note that neither fwait nor waitcond allow 
       arbitrary perl (e.g. 'do{}') in the boolean expression.
   <li><b>waitcond.timeout</b> is an extended version of Piotr Roszatycki's script.
       It runs a command and kills it after a period. The
       timelimit specification allows using a command such as waitcond.
   <li><b>zap</b> (perl) has come a long way from the its old incarnation in the camel book. 
       Nowadays it lists, nices or kills processes or process trees 
       matching a regex with or without user interaction.
</ul>


[*}*][# MUST BE AT EOF! #]
