[*
   $ENV{__EMB_EXTRATITLE}="configuration examples";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Currently,  there's  only  the <B>mc</B>  configuration  available,
while some <b>firefox Chrome</b> is in the firefox section.</p>


<p>Maybe  I'll add some of my mutt setup later on, but the wrapper  to
use  mutt  for  reading  folders in nn style is  probably  a  bit  too
specific,  which my procmail setup is probably way too much glue for a
proper release (incl. mlnn/cron/procmail?) (<i>Q: is procmail stale or
still maintained?</i>).</p>


[*}*][# MUST BE AT EOF! #]
