[*
   $ENV{__EMB_EXTRATITLE}="Minor List Processing Tools";
   $ENV{__EMB_EXTRAMETA}="randomcat, echo2cat, pipe selector examples in curses and gtk2, teefork, tail";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>Some additional small tools for lists and pipes.</p>

<H3>Commands</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.list.various/">Git
    View of this section / Download</a></p>


<ul>
   <li><B>ddnonblock, ddsponge</b> (not actually dd, just mnemonically named commands; 
       GNU dd: use both BS=HUGENUMBER <i>and</i> OBS to force acting like a sponge)
   <li><b>echo2cat</b> (abusing cat0 to turn command arguments into input lines)
   <li><b>line.print, line.replace</b>: combined with grep/grep -v
       the scripts allow basic line-editing using single line commands,
       with the strings being a mostly verbatim part of the command arguments,
       a history of the commands is already part-way to creating an UNDO log
       for basic editing actions.
   <li>a modified version of <b>pfind</b> (find with regex)
   <li><b>pipe.exec</b>: pipe helper
   <ul>
      <li>set return code according to pipe contents (data/no data/grep)
      <li>conditionally execute a command depending on contents (data/no data/grep) and return the programs return code
      <li>tempfile wrapper: copy stdin to tempfile, edit non-stdin-friendly programm arguments and invoke it as part of a pipe (tempfile substituion a la xargs -I{})
   </ul>
   <li><b>pipe.select.curses, pipe.select.gtk2</b> (examples to select lines within pipes)
   <li><b>range</b> (yet another command to print numeric ranges, with/without leading 0)
   <li><b>randomecho</b>, <b>randomcat</b>
   <li><b>revdatesort</b>
   <li><b>sort.ip4</b>
   <li><b>teefork</b> (slightly modified version of the old process-fork-capable perl tee script; forking a pipe into multiple short pipes)
   <li>tailing files: <b>USR1tail</b>, <b>busythreadtail</b>
   
</ul>
   
<p>See also:</p>
<ul>
   <li><a href="../cli.shell.functions/00_SHELL_SETUP.html"><b>f2a</b></a>
        in 00_lib.func: a shell function reading a file into an array.
   <li><b>pipe.vim (aka vimpipe) , vimless</b> to run vim in the middle of a pipe or
       as a less replacement. Both are in the <a href="../vim/00_VIM.html">vim section</a>.
</ul>

[*}*][# MUST BE AT EOF! #]
