#!/bin/sh
# just a memory hint
# alternatives: 
# - 'perl -0pe "use ARGV::readonly"' # module final NL
# - gnu dd ibs=201M bs=200M          # bs and one of ibs/obs required
#                                    # as it ignores buffering otherwise
sponge ${1:+"$@"}

# # e.g. like find DIR1 | sponge | cpio pmd DIR1/x 
# # were you want later actions not mess up earlier
# # ones in the pipe (redirects would trivially
# # solve it, but require more syntactic sugar) 
