#!/bin/sh

# usage e.g. cat README | rsh kefk "cat - | ~jakobi/bin-shared/myenscript" ...

PATH="$PATH:/usr/bin:/usr/local/bin:$HOME/bin:$HOME/bin-shared:/home/jakobi/bin:/home/jakobi/bin-shared";

MYENSCRIPTPRT=${MYENSCRIPTPRT:-$MYPSNUPPRT}
MYENSCRIPTPRT=${MYENSCRIPTPRT:-$PRINTER}
[ "$MYENSCRIPTPRT" = "" ]   && MYENSCRIPTPRT=lj
[ "$MYENSCRIPTFMT" = "" ]   && MYENSCRIPTFMT="-1 --nup 4 --portrait -L 72 -fCourier9"
[ "$MYENSCRIPTOPT" = "" ]   && MYENSCRIPTOPT="" # -l
[ "$MYA2PSOPT"     = "" ]   && MYA2PSOPT="" # -l
[ "$MYLPROPT"      = "" ]   && MYLPROPT="" # -l
MYENSCRIPT=enscript
MYA2PS=a2ps

CMD=$MYENSCRIPT
loop=1; while [ "$1" != "" -a "$loop" ]; do
   case "$1" in
      -P|-d)      MYENSCRIPTPRT=$2; shift ;;
      -P*)        MYENSCRIPTPRT=${1##-P} ;;
      -d*)        MYENSCRIPTPRT=${1##-d} ;;
      -8)         MYENSCRIPTFMT="-1 --nup 8 --portrait -L 72" ;; # -fCourier7"
      -4)         MYENSCRIPTFMT="-1 --nup 4 --portrait -L 72 -fCourier9" ;;
      -4w)        MYENSCRIPTFMT="-1 --nup 4 --portrait -L 90 -fCourier7" ;;
      -2)         MYENSCRIPTFMT="-1 --nup 2 --portrait -L 72" ;;
      -1)         MYENSCRIPTFMT="-1 --nup 1 --portrait -L 72" ;;
      -2w|-w)     CMD=a2ps; MYENSCRIPTFMT="-2 -l166" ; FOLD=165 ;;
                  # instead of explicit fold -165 (implicit default; may be -f option in some implementations of a2ps)
                  # 132 lines, 166 wide (implicitly)
                  # | pr -f -s -l 200 -h "$i"
      -1w|-ww) CMD=a2ps; MYENSCRIPTFMT="-1 -l237" ; FOLD=236 ;; 
                  # -l 237: 237 col, 198 lines (=3*A4)
                  # -l 316: 316 col, 264 lines (=4*A4)
      *)     loop=""; continue ;;
   esac
   shift
done
if test "$1" = "-"; then default=/dev/stdin; shift; fi
default=""; test "$1" = ""   && default=/dev/stdin

# site specific printer shortcut name remapping -> do this in mypsnup!
[ "$MYENSCRIPTPRT" = "oj" ] && MYENSCRIPTPRT=ojmono

for i in $default "$@"; do
   test "$i" = "" && continue
   echo "using $CMD with printer $MYENSCRIPTPRT";
   case $CMD in 
     *enscript*) $MYENSCRIPT $MYENSCRIPTFMT $MYENSCRIPTOPT -G --mark-wrapped-lines=arrow -MA4dj --pass-through -p - "$i" | mypsnup -1 -P$MYENSCRIPTPRT ;;
     *a2ps*)
            # a2ps and manpage differ regarding -f and -n, -nP, --center-title, ...
            # at least folding is still implicit default
            # $MYA2PS $MYENSCRIPTFMT $MYENSCRIPTOPT "$i" -b -P $MYENSCRIPTPRT ;;
	    # -o - : output ps to stdout (instead of -nP)
	    # enscript does this automatically - possibly also handle BS-embolding and underlining; see a4print4 for deskjets
            perl -e 'while(<>){s/([^\x8\x9\xA\xC\x20-\x7E\xA0-\xFF])/"&#0x".unpack(H2,$1).";"/ge; print}' "$i" | \
            $MYA2PS "--center-title=$i" $MYENSCRIPTFMT $MYA2PSOPT -b -o - | mypsnup -1 -P$MYENSCRIPTPRT ;;
     *) $CMD ;;
   esac
done

# to use e.g. highlight: enscript --filter="rcsdiff %s | diffpp %s" -e *.c

# /etc/enscript.cfg - A4dj is offical media
#    Media:  A4              595     842     24      24      571     81
#    Media:  A4dj            595     842     24      50      571     818

