[*
   $ENV{__EMB_EXTRATITLE}="TagLS - Tags and Commandline";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]


<H2>Etymology: Tags Is Derived From TagLs</H2>

<p>[taggl:s]</p>

<p>"speaking names" or<BR>
<a href="http://en.wikipedia.org/wiki/Tag">en.wikipedia.org/wiki/Tag</A> or<BR>
comp/lang/perl/authors/wall,larry/perl.script.process.zap:regex-based-kill</p>

<p>Why  try to store meta information / tags in extra data bases?  Why
modify  file  formats  and  store  meta  information  with  the  file,
requiring  an  extra open or an extra data base? The most  often  used
tags can far simpler be used to make up the file name. Use the primary
hierarchic  relationship for the directory tree, then add a command to
find matching files using arbitrary tag combinations.</p>

<p>A  trivial  find  | grep go a long way when using  the  above  idea
(those  pesky Unix concepts, you remember?). Two ways to improve  this
are  1.  doing  find ahead of time (trivial), 2. getting  rid  of  the
notion of order usually implied by the arguments to grep.</p>

<p>Some                       Larry-Wall-esque                      <A
HREF="http://www.google.com/search?as_q=TIMTOWTDI&hl=en&num=50">TIMTOWTDI
(google  it :)!)</a> to allow more flexibility in the search arguments
doesn't hurt either. A bit of classical logic might just be the ticket
to deal with point two - and if we extend regexes beyond perl's native
capabilities  while  still  being lazy and true to Perl, so  much  the
better: Behold <B>tagls</B>.</p>

<p><i>If  you  are using tags as part of filenames (or just  'speaking
filenames'),  then you may also be interested in tagls, which  handles
searching  in  filelists  with  word boundaries  for  'tags',  synonym
expansion,   boolean  expressions  over  lists  of  tags  or   regular
expressions;  both  against  the  file name or  maybe  also  a  file's
content.   The   output  can  be  unsorted  /  sorted  /   sorted   by
relevance.</i></p>

<p  class=anno>If  you use tagls with e.g. vim and a vim  script  like
utl.vim  you've a pretty useful setup, that is also capable of jumping
between  files  (even  without utl: gqf,  &lt;VISUAL&gt;qf)  and  less
restricted  than say a wiki (provided you do not need html export, for
which the wiki syntax and restrictions are most helpful:)).</p>

<p><B>tagls</B>   and  <B>taglsc</B>  are  an  experiment   of   using
file-system  based tags with scripts and the command line. IMHO  quite
successful,  very useful, and without requiring a heavyweight fulltext
indexer   you've   to  keep  from  running  amok   in   your   archive
directories.</p>

<p  class=anno>If you just remembered Hans Reiser's ideas on semantics
and  filesystems:  his papers offer indeed interesting usage ideas  on
tags, some of which are adaptable to tagls.</p>



<H3>Major Commands</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.list.tagls/">Git
    View of this section / Download</a></p>


<ul>
   <li><B>tagls</B> is a specialized grep implementing boolean expressions over
         word (tags), word lists (taglists), regular expressions and perl scraps,
         enforcing word boundary surrounding tags, allowing for synonyms and
         stemming. It greps a filelist for suitable matching files and optionally
         can also grep inside candidate matches. Results can be highlighted or
         ordered by relevance. Dependencies: expansyn (see cli.list.grep/*).
         Change $shell in the script to use a shell other than bash, any
         Bourne-style shell should do. Published on 
         <a href="http://freshmeat.net/projects/tagls">freshmeat</a>.
   <li><b>taglsc</b> is a wrapper adding document collections to tagls, by
         allowing the user to associate filelists with collectionnames, and
         then invoking tagls with a suitable filelist as input.
         taglsgrep finally is a wrapper to reconfigure tagls to behave
         as a grep against stdin.
<ul>



[* } *][# MUST BE AT EOF! #]
