[*
   $ENV{__EMB_EXTRATITLE}="List Processing incl. Mass-Editing";
   $ENV{__EMB_EXTRAMETA}="cat0: converting from and to null-terminated lines. Grep.pm, Grep.xchange, expansyn: grep with synonym expansion and text replacement/substitution. About Regular Expressions and Stream-Editing.";
   $ENV{__EMB_COUNT}++; 
   if (1==$ENV{__EMB_COUNT}) {
      Execute('base.epl');
   } else {
*]

<p>This  toolbox compartment contains the heavy lifting tools for generic
pipeline 'line'-based text processing.</p>


<H3>About Stream-Editing aka Mass-Editing</H3>

<p>I think extending the range of grep usability to allow mass-editing
files  makes for a nice and powerful concept. This is demonstrated  in
Grep.xchange  below, provided the editing is more or less contained in
the  grepped lines. But there are also other very useful  mass-editing
(=non-interactive   aka  stream-editing)  methods  to  add   to   your
toolbox:</p>

<p>From  perl  -i.bak -lne ... and sed -i.bak -e ... to a more  mature
implementation       of      stream-editing      such      as       <a
href="http://cpan.org/authors/id/L/LE/LEAKIN/">Lee   Eakin's  ped</a>,
which  is  somewhat like a sed-done-right rewrite in perl, with  flock
and  everything. Then there are more generic apps, that in a  specific
domain  are <b>very</b> suitable for mass-edits. Let me give just some
examples from the field of system-administration, more specific system
and         network        configuration        management:         <A
HREf="http://cfengine.org">cfengine</a>,                            <a
href="http://freshmeat.net/projects/puppet">puppet</a>,  or the  'tool
cluster'                             of                             <a
href="http://augeas.net">augeas</a>/pad/boomerang
(PEGs and lenses!).</p>

<p>From  patching to vimming: Don't forget about patch (and check  out
the   way   it   is  used  by  Grep.xchange)  and   a   true   classic
interactive/non-interactive  line editor that provided the first  base
format                  for                 patch:                  <a
href="http://en.wikipedia.org/wiki/Ed_%28text_editor%29">ed</a>;   its
ex  successor embedded within e.g. <a href="http://vim.org">vim</a> is
still  quite similar. With the <a href="../vim/">vimscript script</a> from
this very archive you can extend the usable stream-editing command-set
to most of vim's commands including normal mode! Just be a bit careful
and   turn  off  unnecessary  niceties  like  syntax-highlighting   or
unlimited undo while editing log files in the 100MB region and beyond.
Combined  with an external language - vim's embedded Python  interface
is probably the most stable - things get truly interesting. That's not
to  say that vim's builtin language is a slouch, but still,  vimscript
is  not quite like Python, Perl or Lisp for elegance,  expressiveness,
speed of writing or community support and range of available modules.</p>

<p>Let's  conclude  this tiny and very subjective overview with a  little
gem                    of                    an                     <a
href="http://www.perl.com/pub/a/2004/10/14/file_editing.html">OR-article
about perl mass-editing techniques</a>.</p>


<h3>Mass-Editing and Regular Expressions</h3>

<p>Non-interactive editing requires some way to describe locations and
ranges in files. Usually this is done with (sets of) both line-numbers
and  regular expressions. In this context you can think of the boolean
regular  expressions of Grep.pm below as just a more convenient way to
combine sub-expressions.</p>

<p><b>Newer  developments to watch</b>: The more recent PEGs (e.g.  in
perl6/Rakudo),  tree parsers+transformations, and lenses are also very
fun  stuff  and  do  extend  the <i>Reach  Of  The  GREP</i>  and  its
expressiveness, while reducing the -ahem- line-noise aspect.</p>

<p><b>A Challenge:</b> Any one up to implementing a <i>prolog interpreter</i>
and using an extended <i>regex/peg engine</i> itself as the implementation of
the  <i>backtracking</i>  code (mail me if you did!) :)? The current  feature
set   of   e.g.  full  perl5.10  regexes  goes  way   beyond   classic
DFA-limits...</p>

<p  class=anno>If  you  want  to  go to the  real  basics  of  regular
expressions  and think about the way PCREs (and worse, Perl5.10's  own
regex  implementation)  defy and bend the classics, do check  out  the
computer   science   terms  of  EBNF,   recursive   descent   parsing,
deterministic  finite  automatons, the Chomsky hierarchy  of  grammars
(esp.   Chomsky-3),  the  Turing-Machine,  and  regular   expressions.
Probably  best  start from back to front and choose wikipedia  as  the
starting  point, but don't forget to look at the seminal papers listed
as references.</p>




<H3>Commands</H3>

<p><a href="http://github.com/jakobi/script-archive/tree/master/cli.list.grep/">Git
    View of this section / Download</a></p>


<ul>
   <li><B>cat0</B> converts from and to \0-terminated lines. Depending on
      invocation it's either a glorified but faster to type
      <tt>perl -ne 'chomp; print "$_\0"'</tt> or a <tt>perl -0ne 's/\0\z//; print "$_\n"'</tt>.
      The GNU tools grep [-z|-Z], sort -z, xargs -0 already provide support. nl0 
      reimplements a primitive nl with support, and xargs0 merely
      exists to allow faster typing of <tt>...| cat0|xargs0</tt>: This allows
      me to forget about IFS, quoting and whitespace in filenames and still have a
      well-behaved xargs doing the 'right thing' (provided you don't insist 
      on using  file names with embedded '\n').
   <li><B>cat0par</B> converts paragraphs into \0 lines and also allows for 
      arbitrary regex-based splitting. An overgrown <tt>perl --0ne/perl -0777ne</tt>.
   <li><B>Grep.pm</B> is a fork of tcgrep, which nowadays has learned about context,
       matching from start or end of file (line count or byte count), size limits,
       and highlighting. It extends matching to boolean expressions structuring 
       regular expressions or even arbitrary perl scraps. It can perform basic
       stemming and synonym-expansion in regular expressions (using expansyn). 
       It also handles \0-lines, paragraphs and file slurping, as well as
       directory recursion and compressed files (both as in tcgrep). Dependencies: expansyn.
       It can masquerade as a perl module. Published on
       <a href="http://freshmeat.net/projects/Grep.pm">freshmeat</a> (together
       with Grep.xchange).
   <li>How about a kind of emv not for mass-renaming filenames, but for
       mass-editing file-contents?<BR>
       <B>Grep.xchange</B> bridges the gap between the grep and patch commands:
       it takes grep output and a perl expression
       and uses both to change an arbitrary number of files by applying
       the expression at each of the grep matches, while
       generating a <i>patch file</i> as its <i>UNDO / REDO log</i>.
       It's a bit paranoid, so combined with edited grep output 
       (or Grep.pm -C -LINES <i>marked grep context output</i>),
       the 3-Step <B>Grep.pm|vim.pipe|Grep.xchange</B> is a rather safe way to 
       mass-edit files.  Dependencies: For flock-locking edited files, you also need to copy
       Compact_pm::Flock.pm; otherwise you can disable it by commenting the use statement. 
   <li><b>expansyn</b> is the command implementing basic English stemming and synonym
       expansion for both <B>Grep.pm</B> / <B>tagls</B>. It uses a configuration file expansyn.cfg 
       containing the synonymlists in perl syntax. I wrote it for 
       automatic expansion of some computer science terms I
       always seem to use in parallel.
</ul>

<p>See also:</p>
<ul>
   <li><a href="../cli.backup/00_BACKUP.html"><b>expanfind</b></a> offers something
       roughly similar to stemming or tagging for filelists, based on list contents
       or filesystem contents
   <li><a href="../cli.shell.functions/00_SHELL_SETUP.html"><b>f2a</b></a>
       in 00_lib.func: a shell function reading a file into an array:<BR>
       <tt>ksh93$      find . -print | f2a -a ARGS; less "$ARGS[@]"</tt><BR>
       <tt>bash$&nbsp; f2a -a ARGS < <(find . -print); less "$ARGS[@]"</tt>
   <li><a href="../vim/00_VIM.html"><b>pipe.vim (aka vimpipe) , vimless</b></a> 
       to run vim in the middle of a pipe or
       as a less replacement. Both are in the vim section.
   <li><i>Alternatives for automatic mass file editing</i> are also the usual suspects:
       stream editors from sed to perl -i.bak and the perl ped script, 
       <a href="../admin.text/00_ADMIN_TEXT.html"><b>selectlines</b></a>, 
       <a href="../cli.list.various/00_LISTPROCESSING2.html"><b>xchange.pl</b></a>
       (both in this archive),
       upto full-featured administration tools like cfengine
       with their support to modify or generate configuration files. At the beginning 
       of Grep.xchange you also find two <b>interative perl one-liner</b> examples that
       interactively ask before each substitution. 
</ul>


[*}*][# MUST BE AT EOF! #]
