#!/bin/bash

# use vi < /dev/tty > /dev/tty within a pipe as xargs/find -exec command

# to fake xargs to do something with the shell - note the required dummy for 
# the shell's own name ($0), which is esp. deadly when using -n 1...
# ( echo "a b"; echo c ) | xargs bash -c 'echo "$@"' dummy
#                                bash -c '...'       dummy 'a b' 'c'
#
# note that find -exec ... \+ should substitute for some xargs uses
# (if available that is)
#
# SMP:     use xargs -P <fan-out> -n <number-of-jobs-per-forked-child>
# cluster: dsh,
#          pdsh (can be used for interactive n-node-shell commands tip style), 
#          pssh (parallel-ssh), and the like
# xargs -P 1 -n 5 fan-out-script-running-5-instances-local/remote-in-parallel
#                 but that will need to wait for the slowest forked instance

# cat0 should be mostly idempotent for \0 input, modulo trailing \0 at EOF
# and splitting input in case of records with embedded \n
cat0 | exec xargs -0 ${1:+"$@"}

# e.g. find | xargs0 -n 1 -iZ diff Z /mnt1/AVI-ARCHIVE/Z
