# invoked only on mc startup
_MC_SHELL=1
IGNOREEOF=2
PROMPT_COMMAND_TITLE_PREFIX="mc - "
. ~/.bashrc

#mc changes the prompt command to pwd>&7;kill -STOP $$ ...
#unset PROMPT_COMMAND
#echo "PC IS $PROMPT_COMMAND" > ~/log

#export PS1="#(\$?)  $_PROMPT_DAY \\t \\u@\\h:\\w\n#mc-\\s$SHNEST (\$?) > "
export PS1="#(\$?) \\t \\u@\\h:\\w\n#mc-\\s$SHNEST (\$?) > "


# somehow I must fill a buffer with EXTERNAL COMMAND OUTPUT,
# for ... ; do COMMAND; done isn't sufficient...
# but now at least in 4.6.0, the prompt prints AFTER the first command
# correctly incl. the error. ALAS, no bell and no other features
# unless I really want to remess with PROMPT_COMMAND & 
# its stupid filehandle 8 STOP-self TRICK as mc subshell
/bin/ls /
/bin/ls /
/bin/ls /
/bin/ls /

export LS_OPTIONS="-N --color=never -T 0"
cd .
